<?php

namespace ReverseAuction\ReverseAuctionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BidsInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BidsInfoRepository extends EntityRepository
{
}
