<?php

namespace ReverseAuction\ReverseAuctionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductInfoRepository extends EntityRepository
{
    public function productDisplay() {

        //$today = new \DateTime();
        return $this->getEntityManager()
                        ->createQuery("SELECT p FROM ReverseAuctionReverseAuctionBundle:ProductInfo p WHERE NOT p.pBidExpiry IS NULL and p.pBidExpiry > :now ORDER BY p.pBidExpiry ASC")
                       // ->setParameter('now', new \DateTime('now'), \Doctrine\DBAL\Types\Type::DATETIME) 
                             
                        ->setParameter('now', new \DateTime('now')) 
                        ->getResult() 
                     
                ;
    }
    
}
