<?php

namespace ReverseAuction\ReverseAuctionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WinnerInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WinnerInfoRepository extends EntityRepository {

    public function findMyQuery() {

        /* $em = $this->getEntityManager();
          $query = $em->createQueryBuilder('w' );
          // ->select('w')
          $query->from( 'ReverseAuctionReverseAuctionBundle:WinnerInfo', 'w')
          //->groupBy('w.bidAmount = :bidAmount')
          //->having($query->expr()->gte($query->expr()->count('w'), 1))
          ;
          return $query; */


        return $this->getEntityManager()
                        ->createQuery("SELECT w FROM ReverseAuctionReverseAuctionBundle:WinnerInfo w GROUP BY w.bidAmount HAVING COUNT(w) = 1")
                        ->setMaxResults(5)     
                        ->getResult() 
                     
                ;
    }

}
